// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace PredictiveMaintenance_Console
{
    public partial class PredictiveMaintenance
    {
        /// <summary>
        /// model input class for PredictiveMaintenance.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"UDI")]
            public float UDI { get; set; }

            [ColumnName(@"Product ID")]
            public string Product_ID { get; set; }

            [ColumnName(@"Type")]
            public string Type { get; set; }

            [ColumnName(@"Air temperatureK")]
            public float Air_temperatureK { get; set; }

            [ColumnName(@"Process temperatureK")]
            public float Process_temperatureK { get; set; }

            [ColumnName(@"Rotational speedRPM")]
            public float Rotational_speedRPM { get; set; }

            [ColumnName(@"TorqueNM")]
            public float TorqueNM { get; set; }

            [ColumnName(@"Tool wearMIN")]
            public float Tool_wearMIN { get; set; }

            [ColumnName(@"Machine failure")]
            public float Machine_failure { get; set; }

            [ColumnName(@"TWF")]
            public float TWF { get; set; }

            [ColumnName(@"HDF")]
            public float HDF { get; set; }

            [ColumnName(@"PWF")]
            public float PWF { get; set; }

            [ColumnName(@"OSF")]
            public float OSF { get; set; }

            [ColumnName(@"RNF")]
            public float RNF { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PredictiveMaintenance.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"UDI")]
            public float UDI { get; set; }

            [ColumnName(@"Product ID")]
            public float[] Product_ID { get; set; }

            [ColumnName(@"Type")]
            public float[] Type { get; set; }

            [ColumnName(@"Air temperatureK")]
            public float Air_temperatureK { get; set; }

            [ColumnName(@"Process temperatureK")]
            public float Process_temperatureK { get; set; }

            [ColumnName(@"Rotational speedRPM")]
            public float Rotational_speedRPM { get; set; }

            [ColumnName(@"TorqueNM")]
            public float TorqueNM { get; set; }

            [ColumnName(@"Tool wearMIN")]
            public float Tool_wearMIN { get; set; }

            [ColumnName(@"Machine failure")]
            public uint Machine_failure { get; set; }

            [ColumnName(@"TWF")]
            public float TWF { get; set; }

            [ColumnName(@"HDF")]
            public float HDF { get; set; }

            [ColumnName(@"PWF")]
            public float PWF { get; set; }

            [ColumnName(@"OSF")]
            public float OSF { get; set; }

            [ColumnName(@"RNF")]
            public float RNF { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PredictiveMaintenance.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
