
// This file was auto-generated by ML.NET Model Builder. 

using PredictiveMaintenance_Console;

// Create single instance of sample data from first line of dataset for model input
PredictiveMaintenance.ModelInput sampleData = new PredictiveMaintenance.ModelInput()
{
    UDI = 2F,
    Product_ID = @"L47181",
    Type = @"L",
    Air_temperatureK = 298.2F,
    Process_temperatureK = 308.7F,
    Rotational_speedRPM = 1408F,
    TorqueNM = 46.3F,
    Tool_wearMIN = 3F,
    TWF = 0F,
    HDF = 0F,
    PWF = 0F,
    OSF = 0F,
    RNF = 0F,
};

// Make a single prediction on the sample data and print results
var predictionResult = PredictiveMaintenance.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Machine_failure with predicted Machine_failure from sample data...\n\n");


Console.WriteLine($"UDI: {2F}");
Console.WriteLine($"Product_ID: {@"L47181"}");
Console.WriteLine($"Type: {@"L"}");
Console.WriteLine($"Air_temperatureK: {298.2F}");
Console.WriteLine($"Process_temperatureK: {308.7F}");
Console.WriteLine($"Rotational_speedRPM: {1408F}");
Console.WriteLine($"TorqueNM: {46.3F}");
Console.WriteLine($"Tool_wearMIN: {3F}");
Console.WriteLine($"Machine_failure: {0F}");
Console.WriteLine($"TWF: {0F}");
Console.WriteLine($"HDF: {0F}");
Console.WriteLine($"PWF: {0F}");
Console.WriteLine($"OSF: {0F}");
Console.WriteLine($"RNF: {0F}");


Console.WriteLine($"\n\nPredicted Machine_failure: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

